# Generated by Django 6.0.1 on 2026-01-13 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
