# Generated by Django 6.0.1 on 2026-01-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
